# Generated by Django 5.2 on 2025-06-21 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('editor', '0001_initial'),
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemNdia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.noticia')),
            ],
            options={
                'verbose_name': 'Item ndia',
                'verbose_name_plural': 'Item ndia',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Ndia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.editor')),
                ('item_ndia', models.ManyToManyField(blank=True, through='ndia.ItemNdia', to='noticia.noticia')),
            ],
            options={
                'verbose_name': 'ndia',
                'verbose_name_plural': 'ndia',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='itemndia',
            name='ndia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ndia.ndia'),
        ),
    ]
