# Generated by Django 5.2 on 2025-06-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome')),
                ('idade', models.IntegerField(default=0, verbose_name='Idade')),
            ],
            options={
                'verbose_name': 'Autor',
                'verbose_name_plural': 'Autor',
                'ordering': ['id'],
            },
        ),
    ]
