# Generated by Django 5.2 on 2025-06-21 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editor',
            name='idade',
        ),
        migrations.AddField(
            model_name='editor',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
    ]
