# Generated by Django 5.2 on 2025-06-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('conteudo', models.TextField(max_length=100, verbose_name='Conteudo')),
                ('dataPublicacao', models.URLField(blank=True, null=True, verbose_name='Data da Publicacao')),
                ('categoria', models.CharField(blank=True, max_length=50, null=True, verbose_name='Categoria')),
                ('fonte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fonte')),
                ('autor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticia',
                'ordering': ['id'],
            },
        ),
    ]
