# Generated by Django 5.2 on 2025-06-21 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autor', '0001_initial'),
        ('categories', '0001_initial'),
        ('fonte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('conteudo', models.CharField(max_length=500, verbose_name='Conteudo')),
                ('dataPublicacao', models.DateField(blank=True, max_length=200, null=True, verbose_name='Data da Publicacao')),
                ('autor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='autor.autor')),
                ('fonte', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='fonte.fonte')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.noticia')),
            ],
            options={
                'verbose_name': 'Item de categoria',
                'verbose_name_plural': 'Itens de categorias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='noticia_category',
            field=models.ManyToManyField(blank=True, through='noticia.NoticiaCategoria', to='categories.category'),
        ),
    ]
