# Generated by Django 5.2 on 2025-06-20 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50, verbose_name='Titulo')),
                ('conteudo', models.TextField(max_length=100, verbose_name='Conteudo')),
                ('dataPublicacao', models.DateField(blank=True, max_length=200, null=True, verbose_name='Data da Publicacao')),
                ('fonte', models.CharField(blank=True, max_length=50, null=True, verbose_name='Fonte')),
                ('autor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Autor')),
                ('categoria', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticia',
                'ordering': ['id'],
            },
        ),
    ]
