# Generated by Django 5.2 on 2025-06-20 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticia', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['id'], 'verbose_name': 'Noticia', 'verbose_name_plural': 'Noticias'},
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.CharField(max_length=500, verbose_name='Conteudo'),
        ),
    ]
