# Generated by Django 5.2 on 2025-06-21 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('noticia', '0002_alter_noticia_options_alter_noticia_conteudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='categoria',
        ),
        migrations.CreateModel(
            name='NoticiaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.category')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='noticia.noticia')),
            ],
            options={
                'verbose_name': 'Item de categoria',
                'verbose_name_plural': 'Itens de categorias',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='noticia',
            name='noticia_category',
            field=models.ManyToManyField(blank=True, through='noticia.NoticiaCategoria', to='categories.category'),
        ),
    ]
