# Generated by Django 5.2 on 2025-06-21 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fonte',
            new_name='Clients',
        ),
    ]
